### ISSUE TITLE
Folder Structure and Project Setup for Better Maintainability

### ISSUE THREAD

**Issue by santoshyadavdev** [Devs-Who-Run/devs-who-run-api#15]
### Discussed in https://github.com/Devs-Who-Run/devs-who-run-api/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **yshashi** December  1, 2024</sup>
# Project Structure Proposal: Improved Maintainability in .NET

## Overview

To improve the maintainability and scalability of the project, I propose the following structured folder organization and naming convention. This structure is designed to make the project modular, developer-friendly, and aligned with best practices in .NET development.

### Main Project (`src`)

The `src` directory will contain the main application code. The project name should represent its functionality or domain. For example:
src/
|── DevsWhoRun.Api/
|── Configurations/
|── Migrations/
|── Modules/
|        ────Auth/
|       ──── Users/
|── Properties/
|── appsettings.json
|── appsettings.Development.json
|── Program.cs
|── Dockerfile

### Detailed Folder Description

- **`Configurations/`**: Contains middleware setup, dependency injection configurations, and other application-wide settings.
- **`Migrations/`**: Stores Entity Framework Core database migration files.
- **`Modules/`**: Feature-based module organization
  - **`Auth/`**: Authentication and authorization-related components
  - **`Users/`**: User management-related components
- **`Properties/`**: Assembly metadata and configuration
- **`appsettings.json`**: Centralized configuration file
- **`appsettings.Development.json`**: Environment-specific configuration
- **`Program.cs`**: Application entry point
- **`Dockerfile`**: Docker containerization configuration

## Benefits of the Proposed Structure

1. **Modularity**
   - Each module (e.g., `Auth`, `Users`) is self-contained within the `Modules` folder.
   - New features can be added or removed independently without affecting unrelated parts of the application.

2. **Maintainability**
   - Clear separation between application code (`src`) and tests (`tests`).
   - Developers can easily locate specific code or tests, reducing onboarding time.

3. **Scalability**
   - The structure supports future growth as features expand into dedicated modules.

4. **Standardization**
   - Follows widely accepted .NET project organization practices, making it easier for contributors to understand and collaborate.

### Projects
- API Project: `DevsWhoRun.Api`
- Integration Tests: `DevsWhoRun.IntegrationTests`
- Unit Tests: `DevsWhoRun.UnitTests`

### Folders
- Use **PascalCase** for folder names (e.g., `Configurations`, `Modules`)
- Subfolders under `Modules` should correspond to specific features or areas of functionality (e.g., `Auth`, `Users`)

## Test Projects Structure
tests/
├── DevsWhoRun.UnitTests/
├── DevsWhoRun.IntegrationTests/

## Additional Notes

- The structure allows for easy expansion and modularization of the application.
- Each module can have its own internal structure (controllers, services, repositories, etc.)
- Keeps the project clean and organized as it grows in complexity
</div>

**Comment by yshashi** [comment]
This issue has been fixed with #16 and can be closed now
